### ISSUE TITLE
Performance: set expire headers

### ISSUE THREAD

**Issue by lordkitsuna** [forbjok/blazebooru-docker#2]
the internal webserver currently doesn't set any expire headers on static content. doing so will increase performance for frequent users as well as reverse proxies. unfortunately it's not something that can be set downstream by an additional reverse proxy the origin needs to deal with these headers.

**Comment by forbjok** [comment]
What static content would that be? I don't believe the internal webserver is, or should be serving any static content when running in docker, that feature only exists for development purposes. It should only be serving the API. Serving of static content, such as uploaded images and frontend files is handled directly by nginx.

**Comment by lordkitsuna** [comment]
does the docker container not contain its own nginx? that would be what I meant. sorry for the vauge wording of web server. i simply know i can't set the headers on my own external nginx as it won't accept more than one location directive when doing reverse proxy

**Comment by forbjok** [comment]
Yes, the docker container does run nginx in its http service. And yes, if it's necessary to set them in the nginx config there, that's certainly something I can do. For that matter, you should easily be able to do that yourself by just editing [the nginx config](https://github.com/forbjok/blazebooru-docker/blob/master/http/nginx/conf.d/blazebooru.conf), if you know how to do it.

**Comment by forbjok** [comment]
I've pushed a commit that should set expires as well as some other cache-control headers for the static content now. Can you test if this fixes your issue?

**Comment by lordkitsuna** [comment]
sorry for the delay in response, looks good lighthouse results are solid closing as resolved
